import os

# Base directories
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
DATA_DIR = os.path.join(BASE_DIR, 'data')
FEATURES_DIR = os.path.join(DATA_DIR, 'features')
DB_PATH = os.path.join(DATA_DIR, 'attendance.db')
STATIC_DIR = os.path.join(BASE_DIR, 'static')

# ArcFace feature files (generated by training script)
ARC_FEATURES_PATH = os.path.join(FEATURES_DIR, 'arcface_features.npy')
ARC_LABELS_PATH = os.path.join(FEATURES_DIR, 'arcface_labels.npy')
ARC_NAMES_PATH = os.path.join(FEATURES_DIR, 'arcface_label_names.json')

# Recognition settings
SIMILARITY_THRESHOLD = 0.45  # Cosine similarity threshold for recognition

# Server settings
HOST = '127.0.0.1'
PORT = 8000

# Active model selection: 'arcface', 'model_a', 'model_b'
# Set in app.py at runtime
ACTIVE_MODEL = 'arcface'
